name: image-scan
description: 'Scan image with StackRox'
inputs:
  central-endpoint:
    description: 'Central endpoint in the format stackrox.contoso.com:443'
    required: true
  api-token:
    description: 'API token with CI permissions'
    required: true
  image:
    description: 'Full name of the image to scan -- gcr.io/stackrox/testimage:5.1'
    required: true
  output:
    description: 'Format of output.  Valid values are json, csv, and pretty'
    required: false
    default: 'json'
  skip-tls-verify:
    description: 'Skip TLS certificate validation'
    required: false
    default: 'false'  
runs:
  using: "composite"
  steps:
    - run: >
        curl -s -k -L -H "Authorization: Bearer ${{ inputs.api-token }}" https://${{ inputs.central-endpoint }}:443/api/cli/download/roxctl-linux --output ./roxctl
      shell: bash
    - run: chmod +x ./roxctl
      shell: bash
    - id: scan-info
      run: |
        ./roxctl image scan -e https://${{ inputs.central-endpoint }}:443 --image ${{ inputs.image }} --output ${{ inputs.output }}
      env:
        ROX_API_TOKEN: ${{ inputs.api-token }}
        ROX_INSECURE_CLIENT_SKIP_TLS_VERIFY: ${{ inputs.skip-tls-verify }}
      shell: bash